name: Auto Fork Repository 
 
on:
  schedule:
    - cron: '0 0 */2 * *'  # 每两天午夜运行 
 
jobs:
  fork-repository:
    runs-on: ubuntu-latest 
 
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3 
 
      - name: Install GitHub CLI 
        uses: actions/upload-artifact@v4  
        with:
          github-cli-version: latest 
 
      - name: Login with GitHub CLI 
        run: |
          gh auth login --with-token <(echo "${{ secrets.GITHUB_TOKEN }}")
 
      - name: Fork the repository 
        run: |
          gh repo fork Hiram-Wong/ZyPlayer
