name: Auto Fork Repository

on:
  schedule:
    - cron: '0 0 */2 * *' # Every 2 days at midnight UTC

jobs:
  fork-repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Octokit
      run: npm install @octokit/rest

    - name: Fork repository
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPO_OWNER: your-username-or-org
        REPO_NAME: your-repo-name
      run: |
        node -e "
          const { Octokit } = require('@octokit/rest');
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          async function forkRepo() {
            try {
              await octokit.repos.createFork({
                owner: Hiram-Wong,
                repo: ZyPlayer
              });
              console.log('Repository forked successfully!');
            } catch (error) {
              console.error('Error forking repository:', error);
            }
          }
          forkRepo();
        "



