name: Auto Fork Repository

on:
  schedule:
    # 每 2 天运行一次（可以选择周五和周日运行，例如）
    - cron: '0 0 */2 * *'

jobs:
  fork-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fork Repository
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPO_OWNER: Hiram-Wong
          REPO_NAME: ZyPlayer
        run: |
          # 使用 GitHub API Fork 仓库
          REPO_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/forks"
          RESP=`curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" ${REPO_URL}`
          echo "Response: $RESP"

          # 检查 Fork 是否成功
          if echo "$RESP" | grep -q '"full_name"'; then
            echo "Fork successful!"
          else
            echo "Fork failed!"
            exit 1
          fi

      - name: Send Notification (Optional)
        uses: appleboy/github-action-send文创微信通知@v1
        if: ${{ success() }}
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          title: 'Fork Repository Successfully'
          body: 'The repository has been successfully forked.'
